### Convert Vector to Diagonal Matrix

Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

Example:
Input:
x = np.array([1, 2, 3])
    output = make_diagonal(x)
    print(output)
Output:
[[1. 0. 0.]
    [0. 2. 0.]
    [0. 0. 3.]]


In [4]:
import numpy as np

def make_diagonal(x):
	n = len(x)
	return [
		[int(x[i]) if i == j else 0 for i in range(n)]
		for j in range(n)
	]

In [5]:
x = np.array([4, 5, 6, 7])
make_diagonal(x)

[[4, 0, 0, 0], [0, 5, 0, 0], [0, 0, 6, 0], [0, 0, 0, 7]]