### Implement K-Fold Cross-Validation

Implement a function to generate train and test splits for K-Fold Cross-Validation. Your task is to divide the dataset into k folds and return a list of train-test indices for each fold.

Example:
Input:
k_fold_cross_validation(np.array([0,1,2,3,4,5,6,7,8,9]), np.array([0,1,2,3,4,5,6,7,8,9]), k=5, shuffle=False)
Output:
[([2, 3, 4, 5, 6, 7, 8, 9], [0, 1]), ([0, 1, 4, 5, 6, 7, 8, 9], [2, 3]), ([0, 1, 2, 3, 6, 7, 8, 9], [4, 5]), ([0, 1, 2, 3, 4, 5, 8, 9], [6, 7]), ([0, 1, 2, 3, 4, 5, 6, 7], [8, 9])]

In [2]:
import numpy as np

def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True):
    """
    Implement k-fold cross-validation by returning train-test indices.
    """
    # Your code here
    indices = np.arange(len(X))
    if shuffle:
        np.random.shuffle(indices)

    folds = np.array_split(indices, k)

    train_test = []

    for i in range(k):
        test_indices = folds[i]
        train_indices = np.concatenate(folds[:i] + folds[i+1:])
        train_test.append((train_indices, test_indices))

    return train_test

In [3]:
X = np.array([0,1,2,3,4,5,6,7,8,9])
y = np.array([0,1,2,3,4,5,6,7,8,9])

k_fold_cross_validation(X, y, k=5, shuffle=True)

[(array([5, 6, 2, 3, 1, 4, 0, 8]), array([7, 9])),
 (array([7, 9, 2, 3, 1, 4, 0, 8]), array([5, 6])),
 (array([7, 9, 5, 6, 1, 4, 0, 8]), array([2, 3])),
 (array([7, 9, 5, 6, 2, 3, 0, 8]), array([1, 4])),
 (array([7, 9, 5, 6, 2, 3, 1, 4]), array([0, 8]))]