### One-Hot Encoding of Nominal Values

Write a Python function to perform one-hot encoding of nominal values. The function should take in a 1D numpy array x of integer values and an optional integer n_col representing the number of columns for the one-hot encoded array. If n_col is not provided, it should be automatically determined from the input array.

Example:
Input:
x = np.array([0, 1, 2, 1, 0])
    output = to_categorical(x)
    print(output)
Output:
        [[1. 0. 0.]
        [0. 1. 0.]
        [0. 0. 1.]
        [0. 1. 0.]
        [1. 0. 0.]]

In [4]:
import numpy as np

def to_categorical(x, n_col=None):
    if n_col is None:
        n_col = len(np.unique(x))

    res = []
    
    for num in x:
        row = [0] * n_col
        row[num] = 1
        res.append(row)

    return res

In [5]:
x = np.array([0, 1, 2, 1, 0])
to_categorical(x)

[[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0]]